name: Deploy para o S3

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubutu-latest

    steps:
      - name: Checkout do codigo
      - uses: actions/checkout@v3

      - name: Instalar dependencias
      - run: npm ci

      - name: Build
      - run: npm run build

      - name: Deploy para S3
        uses: jakejarvis/s3-sync-action@master
        with: 
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: dist
    
      


